services:
    open-webui:
        image: 'ghcr.io/open-webui/open-webui:main'
        container_name: open-webui
        restart: on-failure
        volumes:
            - 'open-webui:/app/backend/data'
        environment:
            - OPENAI_API_KEY=${openai_key}
        ports:
            - '3200:8080'

volumes :
  open-webui:{}
network :
  app-network:
    driver: bridge